### ISSUE TITLE
I have a question about the baseline name in the code :)

### ISSUE THREAD

**Issue by shlee-home** [mrxiliang/sstsc#1]
Hi, I have a question about the name of baselines, such as SemiTime, MTL, etc., in the source code.
I think the baseline name differed between the code and the paper.

I guess as below:
[baseline name in the code] -> [baseline name in the paper]
Forecast -> MTL,
SemiIntra -> SemiTime,
...

Is it correct? If it is wrong, please let me know about it.

**Comment by mrxiliang** [comment]
We have checked the code and the baselines' code did have the problem you mentioned. We updated the code, please recheck it, but we did not include all the baselines, SemiTimes please check its link: https://github.com/haoyfan/SemiTime.

**Comment by shlee-home** [comment]
Thanks for your kind :)
